# Generated by Django 2.1.7 on 2019-03-05 20:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='doctors_notes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleteOn', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='doctors_visits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=200, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('doctors_name', models.CharField(max_length=200, null=True)),
                ('deleteOn', models.CharField(max_length=100, null=True)),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='medication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('dosage', models.CharField(max_length=200, null=True)),
                ('deleteOn', models.CharField(max_length=100, null=True)),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(max_length=750)),
                ('deleteOn', models.CharField(max_length=100, null=True)),
                ('doctors_visits', models.ManyToManyField(blank=True, through='website.doctors_notes', to='website.doctors_visits')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='doctors_notes',
            name='doctors_vist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.doctors_visits'),
        ),
        migrations.AddField(
            model_name='doctors_notes',
            name='notes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.Notes'),
        ),
    ]
